async (page) => {
  const result = {};
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  for (const context of page.context().browser().contexts()) if (context !== page.context()) await context.close();
  await page.evaluate(async () => { const g = await import("./src/state.js"); Object.assign(g.state.coffeeShopProgress, { step: "new", orderIndex: 4, ingredientIndex: 0, mistakes: 0 }); g.checkpoint(); });
  await page.reload();
  await page.getByRole("button", { name: "CONTINUE YOUR STORY →" }).click();
  await page.getByRole("button", { name: "☕ Coffee shop", exact: true }).click();
  for (const name of ["SHOT", "MILK", "HONEY"]) await page.getByRole("button", { name, exact: true }).click();
  await page.getByRole("button", { name: "HOLD TO POUR" }).focus();
  await page.keyboard.down("Space");
  await page.waitForTimeout(1000);
  await page.keyboard.press("Escape");
  await page.keyboard.up("Space");
  const before = await page.locator("#pour-fill").getAttribute("style");
  const day = await page.locator("#game-day").innerText();
  await page.waitForTimeout(3800);
  result.pauseFreezesBrewAndDay = before === await page.locator("#pour-fill").getAttribute("style") && day === await page.locator("#game-day").innerText();
  await page.getByRole("button", { name: "SETTINGS & CONTROLS" }).click();
  await page.getByLabel("Reduced motion", { exact: false }).check();
  result.reducedMotionClass = await page.locator("body").evaluate(el => el.classList.contains("reduce-motion"));
  await page.getByLabel("Reduced motion", { exact: false }).uncheck();
  await page.getByLabel("Game sound", { exact: true }).check();
  await page.getByLabel("Music", { exact: false }).fill("24");
  await page.getByRole("button", { name: "DONE", exact: true }).click();
  await page.getByRole("button", { name: "RESUME →", exact: true }).click();
  await page.getByRole("button", { name: "HOLD TO POUR" }).focus();
  await page.keyboard.down("Space"); await page.waitForTimeout(900);
  await page.screenshot({ path: "output/playwright/01-coffee.png", scale: "css" });
  await page.keyboard.up("Space");
  await page.getByRole("button", { name: "Ⅱ MENU", exact: true }).click();
  await page.reload();
  result.continuePresent = await page.getByRole("button", { name: "CONTINUE YOUR STORY →" }).isVisible();
  await page.getByRole("button", { name: "CONTINUE YOUR STORY →" }).click();
  result.brewSurvivesReload = await page.getByRole("button", { name: "SERVE MARA →", exact: true }).isVisible();
  await page.getByRole("button", { name: "Ⅱ MENU", exact: true }).click();

  // Fault-injection context: isolated storage denial and actual touch events.
  const context = await page.context().browser().newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  await context.addInitScript(() => Object.defineProperty(window, "localStorage", { get() { throw new DOMException("Blocked by test", "SecurityError"); } }));
  const mobile = await context.newPage();
  mobile.on("pageerror", error => errors.push("mobile: " + error.message));
  await mobile.goto("http://127.0.0.1:8770/index.html");
  await mobile.getByRole("button", { name: "OPEN THE COFFEE SHOP →" }).tap();
  for (const name of ["SHOT", "MILK", "HONEY"]) await mobile.getByRole("button", { name, exact: true }).tap();
  const target = mobile.getByRole("button", { name: "HOLD TO POUR" });
  await target.scrollIntoViewIfNeeded();
  const box = await target.boundingBox();
  const cdp = await context.newCDPSession(mobile);
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: box.x + box.width / 2, y: box.y + box.height / 2 }] });
  await mobile.waitForTimeout(2825);
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  result.touchPour = await mobile.locator(".arcade-panel").innerText();
  await mobile.waitForTimeout(400);
  await mobile.getByRole("button", { name: "SERVE MARA →", exact: true }).tap();
  await mobile.waitForTimeout(800);
  result.noHorizontalOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
  result.storageDeniedPlayable = await mobile.getByRole("heading", { name: "Cinnamon cappuccino" }).isVisible();
  await mobile.screenshot({ path: "output/playwright/mobile.png", fullPage: true, scale: "css" });
  await context.close();

  // Controlled late-game fixture verifies the ending without farming test money.
  await page.evaluate(async () => {
    const game = await import("./src/state.js");
    for (let i = 0; i < 45; i++) game.tick();
  });
  await page.getByRole("button", { name: "RESUME →", exact: true }).click();
  await page.getByRole("button", { name: "REVIEW YOUR BEST PARCEL →" }).click();
  await page.getByRole("button", { name: /^Sell for/ }).click();
  await page.getByRole("button", { name: "COLLECT $1,100 →", exact: true }).click();
  await page.evaluate(async () => { const game = await import("./src/state.js"); game.state.money = 3900; game.checkpoint(); });
  await page.getByRole("button", { name: "✦ Goal", exact: true }).click();
  await page.getByRole("button", { name: /BUY THE RED ROADSTER/ }).click();
  await page.waitForTimeout(2900);
  await page.screenshot({ path: "output/playwright/03-homecoming.png", scale: "css" });
  await page.getByRole("button", { name: "OPEN THE TRUNK →" }).click();
  await page.getByRole("button", { name: "Skip conversation" }).click();
  result.endingReport = await page.getByRole("heading", { name: "GOAL ACHIEVED!" }).isVisible();
  await page.getByRole("button", { name: "CONTINUE", exact: true }).click();
  await page.getByRole("button", { name: "Ⅱ MENU", exact: true }).click();
  await page.getByRole("button", { name: "TITLE SCREEN", exact: true }).click();
  await page.getByRole("button", { name: "NEW GAME", exact: true }).click();
  await page.getByRole("button", { name: "START NEW GAME", exact: true }).click();
  result.restartClearsRun = await page.locator("#money").innerText() === "$120";
  await page.getByRole("button", { name: "Ⅱ MENU", exact: true }).click();
  result.errors = errors;
  return result;
}
